apiDebug: true
timeout: 600000

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    # Use nodeUrl from credentials.js
    url: "${credentials.nodeUrl}"
    # Use nodePublicKey from credentials.js
    publicKey: "${credentials.nodePublicKey}"
    port: 30303
    oauth:
      appTokenCookieName: "blockapps_sample_session"
      scope: "email openid"
      appTokenCookieMaxAge: 7776000000 # 90 days: 90 * 24 * 60 * 60 * 1000
      # Use clientId from credentials.js
      clientId: "${credentials.clientId}"
      # Use clientSecret from credentials.js
      clientSecret: "${credentials.clientSecret}"
      openIdDiscoveryUrl: "https://keycloak.blockapps.net/auth/realms/mercata/.well-known/openid-configuration"
      redirectUri: 'http://localhost:3000/api/v1/authentication/callback'
      logoutRedirectUri: "https://localhost:3000"
